project:
  type: book

book:
  title: "IT-Security Lecture Notes WS24/25"
  author: "Igor Dimitrov"
  date: "10/14/2024"
  chapters:
    - index.qmd
    - intro.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



